package io.github.stefanbratanov.jvm.openai;

import java.util.List;

/** Represents a chat completion response returned by model, based on the provided input. */
public record ChatCompletion(
    String id,
    long created,
    String model,
    String serviceTier,
    String systemFingerprint,
    List<Choice> choices,
    CompletionUsage usage) {

  public record Choice(int index, Message message, Logprobs logprobs, String finishReason) {

    /** A chat completion message generated by the model. */
    public record Message(String content, String refusal, List<ToolCall> toolCalls, String role) {}
  }
}
