package io.github.stefanbratanov.jvm.openai;

/**
 * Usage statistics for the completion request.
 *
 * @param completionTokensDetails Breakdown of tokens used in a completion.
 */
public record CompletionUsage(
    int completionTokens,
    int promptTokens,
    int totalTokens,
    CompletionTokensDetails completionTokensDetails) {

  /**
   * @param reasoningTokens Tokens generated by the model for reasoning.
   */
  public record CompletionTokensDetails(Integer reasoningTokens) {}
}
