package io.github.stefanbratanov.jvm.openai;

import java.util.List;
import java.util.Optional;

public record FineTuningJobIntegration(String type, Wandb wandb) {

  public record Wandb(
      String project, Optional<String> name, Optional<String> entity, Optional<List<String>> tags) {

    public static Builder newBuilder() {
      return new Builder();
    }

    public static class Builder {

      private String project;
      private Optional<String> name = Optional.empty();
      private Optional<String> entity = Optional.empty();
      private Optional<List<String>> tags = Optional.empty();

      /**
       * @param project The name of the project that the new run will be created under.
       */
      public Builder project(String project) {
        this.project = project;
        return this;
      }

      /**
       * @param name A display name to set for the run. If not set, we will use the Job ID as the
       *     name.
       */
      public Builder name(String name) {
        this.name = Optional.of(name);
        return this;
      }

      /**
       * @param entity The entity to use for the run. This allows you to set the team or username of
       *     the WandB user that you would like associated with the run. If not set, the default
       *     entity for the registered WandB API key is used.
       */
      public Builder entity(String entity) {
        this.entity = Optional.of(entity);
        return this;
      }

      /**
       * @param tags A list of tags to be attached to the newly created run. These tags are passed
       *     through directly to WandB. Some default tags are generated by OpenAI:
       *     "openai/finetune", "openai/{base-model}", "openai/{ftjob-abcdef}".
       */
      public Builder tags(List<String> tags) {
        this.tags = Optional.of(tags);
        return this;
      }

      public Wandb build() {
        return new Wandb(project, name, entity, tags);
      }
    }
  }

  public static FineTuningJobIntegration wandbIntegration(Wandb wandb) {
    return new FineTuningJobIntegration(Constants.WANDB_INTEGRATION_TYPE, wandb);
  }
}
