package io.github.stefanbratanov.chatjpt;

import java.util.List;

/** Represents a chat completion response returned by model, based on the provided input. */
public record ChatResponse(
    String id,
    long created,
    String model,
    String systemFingerprint,
    List<Choice> choices,
    Usage usage) {

  public record Choice(int index, Message message, Logprobs logprobs, String finishReason) {

    /** A chat completion message generated by the model. */
    public record Message(String content, List<ToolCall> toolCalls, String role) {}
  }

  public record Usage(int promptTokens, int completionTokens, int totalTokens) {}
}
